# Generated by Django 4.2.11 on 2024-10-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertranslationhistory',
            name='targetText',
            field=models.TextField(blank=True),
        ),
    ]
