# Generated by Django 4.2.11 on 2024-10-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlm_app', '0002_alter_usertranslationhistory_targettext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertranslationhistory',
            name='sourceLanguage',
            field=models.CharField(choices=[('auto', 'Auto-Detect'), ('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('it', 'Italian')], default='auto', max_length=4),
        ),
        migrations.AlterField(
            model_name='usertranslationhistory',
            name='targetLanguage',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('it', 'Italian')], default=('en', 'English'), max_length=2),
        ),
    ]
