# Generated by Django 4.2.11 on 2024-10-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlm_app', '0003_alter_usertranslationhistory_sourcelanguage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertranslationhistory',
            name='targetLanguage',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('it', 'Italian')], default='en', max_length=2),
        ),
    ]
