# Generated by Django 4.2.11 on 2024-10-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlm_app', '0004_alter_usertranslationhistory_targetlanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertranslationhistory',
            name='sourceLanguage',
            field=models.CharField(choices=[('auto', 'Auto-Detect'), ('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('it', 'Italian')], default=('auto', 'Auto-Detect'), max_length=4),
        ),
    ]
