# Generated by Django 4.2.11 on 2024-10-25 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlm_app', '0008_usersettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlistobject',
            old_name='listTile',
            new_name='listTitle',
        ),
    ]
