# Generated by Django 4.2.11 on 2024-10-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlm_app', '0009_rename_listtile_userlistobject_listtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='defaultLanguage',
            field=models.CharField(default='English', max_length=25),
        ),
    ]
